[package]
name = "di-api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.195"
futures = "0.3.30"
tokio = {version = "1.35.1", features = ["full"]}

[dependencies.mongodb]
version = "2.8.0"
features = ["tokio-runtime"]

[dev-dependencies]
rustfmt = "0.10.0"
clippy = "0.0.302"
