[package]
name = "di-api"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot = "0.12.1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.35.1", features = ["full"] }
warp = "0.3.6"
http = "1.0.0"

[dependencies.mongodb]
version = "2.8.0"
features = ["tokio-runtime"]

[dev-dependencies]
rustfmt = "0.10.0"
clippy = "0.0.302"
